apiVersion: v1
kind: Service
metadata:
  name: config-wiki-tailscale
  namespace: config-wiki-staging
  annotations:
    tailscale.com/hostname: "config-wiki"
spec:
  selector:
    app: config-wiki
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer
  loadBalancerClass: tailscale
